openapi: 3.1.0
info:
  title: Semantic Kernel Plugin
  description: A plugin that allows the user to call Semantic Kernel Functions.
  version: 'v1'
servers:
  - url: http://localhost:5050
paths:
  /skills/math:
    post:
      operationId: mathskills
      description: |
        Execute the math semantic function; submit the prompt as a JSON object in the payload, e.g. {"prompt": "square root of 64?"}
      requestBody:
        required: True
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/executeMathSkillFunctionRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    executeMathSkillFunctionRequest:
      type: object
      properties:
        prompt:
          type: string
      required:
        - prompt