openapi: 3.1.0
info:
  title: Microsoft Semantic ChatGPT Plugin
  description: Example API for Math Skills Plugin
  version: v1.0
servers:
- url: http://localhost:7071
  description: Default server
paths:
  "/.well-known/ai-plugin.json":
    get:
      operationId: AIPluginHandler.get
      summary: ChatGPT manifest file, ai-plugin.json
      description: ''
      parameters: []
      responses:
        '200':
          description: openapi manifest in application/json format
          content:
            text/plain:
              schema:
                type: string
  "/openapi.yaml":
    get:
      operationId: OpenAPIHandler.get
      summary: ChatGPT will use this route to find our API specification, openapi.yaml
      description: ''
      parameters: []
      responses:
        '200':
          description: openapi API specification in text/yaml format
          content:
            text/plain:
              schema:
                type: string
  "/skills/math":
    post:
      operationId: MathSkill.post
      summary: Microsoft Semantic Math Plugin Example Using OpenAI
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/MathSkillBody"
      responses:
        '200':
          description: Response with initial request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/MathResult"
        '500':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorResponse"
components:
  schemas:
    ErrorResponse:
      type: object
      description: 'Error response object.'
      required:
      - code
      properties:
        code:
          type: integer
          description: Error code.
        error:
          type: string
          description: Error description.
    MathSkillBody:
      type: object
      description: 'Math Skill result object.'
      properties:
        prompt:
          type: string
          description: Requested user prompt
    MathResult:
      type: object
      description: 'Math Skill result object.'
      properties:
        result:
          type: string
          description: Math skill result in json format string